### ISSUE TITLE
Need a test

### ISSUE THREAD

**Issue by kbroman** [yzhang672/Frenchpj#4]
One last thing: I'd like you to add a test or two for one or more of your functions.

The [`testthat.R`](https://github.com/yzhang672/Frenchpj/blob/master/SpeClust/testthat.R) file should be sitting in a `tests/` subdirectory, and there should be a `tests/testthat/` subdirectory that contains some tests.

See <http://kbroman.org/pkg_primer/pages/tests.html> and let me know if you need help.

**Comment by yzhang672** [comment]
Hi Prof. Karl,

I just added a test file. Do you mean this?

I am not sure how to add test for specific functions...

Best,
Yilin

**Comment by kbroman** [comment]
The `testthat.R` file on it's own doesn't do much. You need to add an R file within the `tests/testthat/` subdirectory that defines a testthat test, something like [this, from the broman package](https://github.com/kbroman/broman/blob/master/tests/testthat/test-myround.R).

**Comment by yzhang672** [comment]
Hi Prof. Karl,

I have added tests for function drop and function combind_fanwords.

Thanks,
Yilin

**Comment by kbroman** [comment]
The tests look good. 

But also see my [pull request](https://github.com/yzhang672/Frenchpj/pull/3): the `@import` statements in your R file weren't working and there was another package dependency that you'd not indicated.

And I'm still getting some issues in `R CMD check`; see [issue #2](https://github.com/yzhang672/Frenchpj/issues/2).

**Comment by yzhang672** [comment]
Hi Prof. Karl,

I revised my R package, but now I have a new error:

file.copy(pkgname, Tdir, recursive = TRUE)���о���:
   
����.\SpeClust\.Rproj.user\AC023CCC\sdb\s-2E90ED92\lock_file��C:\Users\ADMINI~1\AppData\Local\Temp\RtmpUdyS6Z\Rbuild8a86898345d\SpeClust\.Rproj.user\AC023CCC\sdb\s-2E90ED92\lock_fileʱ�������⣺Permission 
denied
  ERROR
copying to build directory failed
����: Command failed (1)
ִֹͣ��

Exited with status 1.



Could you please tell me how can I fix it?

Thanks,
Yilin

**Comment by kbroman** [comment]
If you can, maybe come by my office hours today at 2:30.

My office is 2126 Genetics/Biotech, at the southwest corner of the building (Henry Mall & Univ).

karl

**Comment by kbroman** [comment]
What are you doing that gives this error?
Try deleting the `.Rproj.user` directory.

**Comment by yzhang672** [comment]
Hi Prof. Karl,

The R check get correct now. But I cannot figure out how to delete the 
.Rproj.user directory. Even on my laptop, I cannot delete that file...

Sorry for making so many troubles...

Yilin

**Comment by kbroman** [comment]
From the command line, 

  git rm -r Rproj.user

Restudy may create it again, but if you have it in .gitignore, git should't bother you about it. 

Karl

**Comment by yzhang672** [comment]
Thanks professor! I deleted the Rproj.user file and .Rhistory file just 
now.

Thanks,
Yilin
